//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPGTEST.IPGToken {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenRequest", Namespace="http://schemas.datacontract.org/2004/07/IpgToken.DataAccess")]
    [System.SerializableAttribute()]
    public partial class TokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallbackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TerminalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillId {
            get {
                return this.BillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIdField, value) != true)) {
                    this.BillIdField = value;
                    this.RaisePropertyChanged("BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackUrl {
            get {
                return this.CallbackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallbackUrlField, value) != true)) {
                    this.CallbackUrlField = value;
                    this.RaisePropertyChanged("CallbackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceIdField, value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantLogo {
            get {
                return this.MerchantLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantLogoField, value) != true)) {
                    this.MerchantLogoField = value;
                    this.RaisePropertyChanged("MerchantLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantName {
            get {
                return this.MerchantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNameField, value) != true)) {
                    this.MerchantNameField = value;
                    this.RaisePropertyChanged("MerchantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadField, value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TerminalId {
            get {
                return this.TerminalIdField;
            }
            set {
                if ((this.TerminalIdField.Equals(value) != true)) {
                    this.TerminalIdField = value;
                    this.RaisePropertyChanged("TerminalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResponse", Namespace="http://schemas.datacontract.org/2004/07/IpgFunction.Models.Response")]
    [System.SerializableAttribute()]
    public partial class TokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccesstokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accesstoken {
            get {
                return this.AccesstokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccesstokenField, value) != true)) {
                    this.AccesstokenField = value;
                    this.RaisePropertyChanged("Accesstoken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPGToken.IToken")]
    public interface IToken {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToken/GetToken", ReplyAction="http://tempuri.org/IToken/GetTokenResponse")]
        IPGTEST.IPGToken.TokenResponse GetToken(IPGTEST.IPGToken.TokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToken/GetToken", ReplyAction="http://tempuri.org/IToken/GetTokenResponse")]
        System.Threading.Tasks.Task<IPGTEST.IPGToken.TokenResponse> GetTokenAsync(IPGTEST.IPGToken.TokenRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenChannel : IPGTEST.IPGToken.IToken, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenClient : System.ServiceModel.ClientBase<IPGTEST.IPGToken.IToken>, IPGTEST.IPGToken.IToken {
        
        public TokenClient() {
        }
        
        public TokenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IPGTEST.IPGToken.TokenResponse GetToken(IPGTEST.IPGToken.TokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public System.Threading.Tasks.Task<IPGTEST.IPGToken.TokenResponse> GetTokenAsync(IPGTEST.IPGToken.TokenRequest request) {
            return base.Channel.GetTokenAsync(request);
        }
    }
}
