//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPGTEST.IpgWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionRequest", Namespace="http://schemas.datacontract.org/2004/07/IpgFunction.Models.Request")]
    [System.SerializableAttribute()]
    public partial class FunctionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DigitalReceiptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DigitalReceipt {
            get {
                return this.DigitalReceiptField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitalReceiptField, value) != true)) {
                    this.DigitalReceiptField = value;
                    this.RaisePropertyChanged("DigitalReceipt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Tid {
            get {
                return this.TidField;
            }
            set {
                if ((this.TidField.Equals(value) != true)) {
                    this.TidField = value;
                    this.RaisePropertyChanged("Tid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionResponse", Namespace="http://schemas.datacontract.org/2004/07/IpgFunction.Models.Response")]
    [System.SerializableAttribute()]
    public partial class FunctionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnId {
            get {
                return this.ReturnIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnIdField, value) != true)) {
                    this.ReturnIdField = value;
                    this.RaisePropertyChanged("ReturnId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IpgWS.IIpg")]
    public interface IIpg {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIpg/RollBack", ReplyAction="http://tempuri.org/IIpg/RollBackResponse")]
        IPGTEST.IpgWS.FunctionResponse RollBack(IPGTEST.IpgWS.FunctionRequest fRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIpg/RollBack", ReplyAction="http://tempuri.org/IIpg/RollBackResponse")]
        System.Threading.Tasks.Task<IPGTEST.IpgWS.FunctionResponse> RollBackAsync(IPGTEST.IpgWS.FunctionRequest fRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIpg/Advice", ReplyAction="http://tempuri.org/IIpg/AdviceResponse")]
        IPGTEST.IpgWS.FunctionResponse Advice(IPGTEST.IpgWS.FunctionRequest fRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIpg/Advice", ReplyAction="http://tempuri.org/IIpg/AdviceResponse")]
        System.Threading.Tasks.Task<IPGTEST.IpgWS.FunctionResponse> AdviceAsync(IPGTEST.IpgWS.FunctionRequest fRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIpgChannel : IPGTEST.IpgWS.IIpg, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IpgClient : System.ServiceModel.ClientBase<IPGTEST.IpgWS.IIpg>, IPGTEST.IpgWS.IIpg {
        
        public IpgClient() {
        }
        
        public IpgClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IpgClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpgClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpgClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IPGTEST.IpgWS.FunctionResponse RollBack(IPGTEST.IpgWS.FunctionRequest fRequest) {
            return base.Channel.RollBack(fRequest);
        }
        
        public System.Threading.Tasks.Task<IPGTEST.IpgWS.FunctionResponse> RollBackAsync(IPGTEST.IpgWS.FunctionRequest fRequest) {
            return base.Channel.RollBackAsync(fRequest);
        }
        
        public IPGTEST.IpgWS.FunctionResponse Advice(IPGTEST.IpgWS.FunctionRequest fRequest) {
            return base.Channel.Advice(fRequest);
        }
        
        public System.Threading.Tasks.Task<IPGTEST.IpgWS.FunctionResponse> AdviceAsync(IPGTEST.IpgWS.FunctionRequest fRequest) {
            return base.Channel.AdviceAsync(fRequest);
        }
    }
}
